apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/julesmuntz/julmuntz.git
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
      version: v1
  template:
    metadata:
      labels:
        app: playground
        version: v1
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  selector:
    app: playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888